import { Court } from './types';

export const INITIAL_COURTS: Court[] = [
  {
    id: 'court-1',
    backendId: 1,
    name: 'Cancha Central Padel 1',
    sport: 'padel',
    type: 'Indoor',
    club: 'Club Raqueta Polanco',
    city: 'CDMX',
    score: 4.9,
    pricePerHour: 20,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCrK7kD9iB7twRwcrmMZeAd-AaejnMF-N5b18ei_MNi77qds9xXqzQu8Y07WfPMAg69oQz6WUHjEIWRolvq34BGGwZKtAjF1tnFAwTBR_mLa9OvGhwmAMJpYA-XHoZ_7ikUbuaVI6fTj1OUwTUMDaOoZ0Cl4BvO_08oXYSSoeRnflr47QDl1EKeXk3njkjQWj70rcMdhzbZyRbksyLrwML9fCW00AklWNpk6Kx0tkA3UkT2ei9FEmOTZ09Yvc51OFAPqBFnYTD8O2g',
    address: 'Campos Elíseos 134, Polanco, CDMX, México',
    isAvailable: true,
  },
  {
    id: 'court-2',
    backendId: 2,
    name: 'Cancha 4 Grand Slam',
    sport: 'tenis',
    type: 'Arcilla',
    club: 'Santa Fe Sports Center',
    city: 'CDMX',
    score: 4.7,
    pricePerHour: 25,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAXdbdq9o3GiNN-V_l13w_uldGx60kVowaAzEAx4zZazcV5P9OayQc6b-GWQIEEcfFJokHpenceEb2K89IMGi5oMek5TIKU7S1BD0rYPxjwuzabujjBeR2sOJ5KKwmu2pRwaJPhaBosVLSv5nteo8_DlboanVkTk7Za1uHSjacYAAuRtNtbGmqt0quQGIVNLBZUQV7buWoUGRBk0C8KiosWC2qphVc3-unqe8bsjA6QXAyeTMxCpTzGALWHbz37R6hTEQWRdjyuKRQ',
    address: 'Av. Vasco de Quiroga 2000, Lomas de Santa Fe, CDMX, México',
    isAvailable: true,
    upcomingSpots: true,
  },
  {
    id: 'court-3',
    backendId: 3,
    name: 'Estadio Urbano Sky 5',
    sport: 'futbol',
    type: 'Sintético',
    club: 'Roof Garden Arena',
    city: 'Roma Norte, CDMX',
    score: 4.8,
    pricePerHour: 30,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB94KbkV0VHtWs83FMAxH31xsdN-r6945eD6mEXUX_pq4vv9ZOc3Ca_SqU93EEoXnCDJJwsdKg_j9Yy7LevuebLGgLiaVqVkysZYgoLH9QZOwnbWEp5CQWPs3LtgBMLcPjsGmgpVqLHL6L14Ce-n4yQi7jhPYrAJNLv8_A4nkvVUR8E3fZoYEOTNMS5ugsPC3_FjPBG6ycZ_k0pfWexLDEt_Te-zx_JyqpZ3ohRvJ2V69V0YW-f68kZB4aYXqW0CMtw1qS69fDrCAs',
    address: 'Álvaro Obregón 154, Roma Norte, CDMX, México',
    isAvailable: true,
  },
  {
    id: 'court-4',
    backendId: 4,
    name: 'Duela NBA Pro',
    sport: 'basquet',
    type: 'Duela',
    club: 'Centro Deportivo Coyoacán',
    city: 'Coyoacán, CDMX',
    score: 5.0,
    pricePerHour: 10,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDRk7imwWYwGKA7htwJtibvnLq9_ZxgVd1gyTQp6cI_x7LBHDjOpj2VSP_G86AukgyCnVRklW72jTPVluij6cbxNCDwOS7oGxNfIxs-0Fwkhtnd1ZdsJE1k75q8AJCAufLsfbJ7dCwmBDQZpxgvVt0YtzGKAPHaoJUCpnjNojxbJ8S7JpCTc4Xc9P6ulVy3XtTJydBYjieYWg_0R3urBn3CIg8XewYQfZ60rbK8kljnQXkrM8M9WXr25idkmGhrNnULMEVCXB3Yf38',
    address: 'Aguayo 23, Culhuacán, Coyoacán, CDMX, México',
    isAvailable: true,
  },
  {
    id: 'court-5',
    backendId: 5,
    name: 'Padel Club Vista Hermosa',
    sport: 'padel',
    type: 'Outdoor',
    club: 'Club Raqueta Lomas',
    city: 'Lomas, CDMX',
    score: 4.6,
    pricePerHour: 15,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDA_eQMsx5tXpfa1XANsqb08FWsoQYxRwq7_7L44hOhTlQ3SAU_uHx-vqbD-RRT7oVBUDWbX5RJXEXcOfQwEBjeFoDtJRjrAB_y8SThEAOUkUgumoWoalFYcA-TFEAdS0LmsyZM-jc6jYRW0f6EUIpZrIg5t3y29iHKLRPGsKixsJYN2mtsnmNgBfJd4IW-PW3kxP2xJK1m4dE6GpYDOPTtwFYjOb9MGSfXZam6POEndF0TS80gWWNjdC5nC2roXpZmAWG9IHy6suU',
    address: 'Paseo de la Reforma 4000, Lomas de Vista Hermosa, CDMX, México',
    isAvailable: false,
  },
  {
    id: 'court-6',
    backendId: 6,
    name: 'Arena Pro Tenis Smash',
    sport: 'tenis',
    type: 'Rápida',
    club: 'Club de Tenis San Ángel',
    city: 'San Ángel, CDMX',
    score: 4.9,
    pricePerHour: 25,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAXdbdq9o3GiNN-V_l13w_uldGx60kVowaAzEAx4zZazcV5P9OayQc6b-GWQIEEcfFJokHpenceEb2K89IMGi5oMek5TIKU7S1BD0rYPxjwuzabujjBeR2sOJ5KKwmu2pRwaJPhaBosVLSv5nteo8_DlboanVkTk7Za1uHSjacYAAuRtNtbGmqt0quQGIVNLBZUQV7buWoUGRBk0C8KiosWC2qphVc3-unqe8bsjA6QXAyeTMxCpTzGALWHbz37R6hTEQWRdjyuKRQ',
    address: 'Altavista 12, San Ángel, Álvaro Obregón, CDMX, México',
    isAvailable: true,
  },
  {
    id: 'court-7',
    backendId: 7,
    name: 'Estadio Campo de Fútbol 7',
    sport: 'futbol',
    type: 'Pasto Sintético Pro',
    club: 'Club Fútbol Condesa',
    city: 'La Condesa, CDMX',
    score: 4.9,
    pricePerHour: 35,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB94KbkV0VHtWs83FMAxH31xsdN-r6945eD6mEXUX_pq4vv9ZOc3Ca_SqU93EEoXnCDJJwsdKg_j9Yy7LevuebLGgLiaVqVkysZYgoLH9QZOwnbWEp5CQWPs3LtgBMLcPjsGmgpVqLHL6L14Ce-n4yQi7jhPYrAJNLv8_A4nkvVUR8E3fZoYEOTNMS5ugsPC3_FjPBG6ycZ_k0pfWexLDEt_Te-zx_JyqpZ3ohRvJ2V69V0YW-f68kZB4aYXqW0CMtw1qS69fDrCAs',
    address: 'Nuevo León 230, Hipódromo Condesa, CDMX, México',
    isAvailable: true,
  },
  {
    id: 'court-8',
    backendId: 8,
    name: 'Padel Dome Satélite',
    sport: 'padel',
    type: 'Techada',
    club: 'Padel Dome Satélite',
    city: 'Naucalpan, Edomex',
    score: 4.8,
    pricePerHour: 25,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCrK7kD9iB7twRwcrmMZeAd-AaejnMF-N5b18ei_MNi77qds9xXqzQu8Y07WfPMAg69oQz6WUHjEIWRolvq34BGGwZKtAjF1tnFAwTBR_mLa9OvGhwmAMJpYA-XHoZ_7ikUbuaVI6fTj1OUwTUMDaOoZ0Cl4BvO_08oXYSSoeRnflr47QDl1EKeXk3njkjQWj70rcMdhzbZyRbksyLrwML9fCW00AklWNpk6Kx0tkA3UkT2ei9FEmOTZ09Yvc51OFAPqBFnYTD8O2g',
    address: 'Circuito Novelistas 20, Ciudad Satélite, Naucalpan, Estado de México',
    isAvailable: true,
    upcomingSpots: true,
  },
  {
    id: 'court-9',
    backendId: 9,
    name: 'Sunset Basket Court',
    sport: 'basquet',
    type: 'Concreto Pro',
    club: 'Unidad Deportiva Cuauhtémoc',
    city: 'CDMX',
    score: 4.5,
    pricePerHour: 10,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDRk7imwWYwGKA7htwJtibvnLq9_ZxgVd1gyTQp6cI_x7LBHDjOpj2VSP_G86AukgyCnVRklW72jTPVluij6cbxNCDwOS7oGxNfIxs-0Fwkhtnd1ZdsJE1k75q8AJCAufLsfbJ7dCwmBDQZpxgvVt0YtzGKAPHaoJUCpnjNojxbJ8S7JpCTc4Xc9P6ulVy3XtTJydBYjieYWg_0R3urBn3CIg8XewYQfZ60rbK8kljnQXkrM8M9WXr25idkmGhrNnULMEVCXB3Yf38',
    address: 'Eje Central Lázaro Cárdenas, Guerrero, CDMX, México',
    isAvailable: true,
  }
];

export const MOCK_TIME_SLOTS = [
  { id: 't1', time: '07:00 - 08:30', period: 'Mañana' },
  { id: 't2', time: '08:30 - 10:00', period: 'Mañana' },
  { id: 't3', time: '10:00 - 11:30', period: 'Mañana' },
  { id: 't4', time: '11:30 - 13:00', period: 'Mañana' },
  { id: 't5', time: '13:00 - 14:30', period: 'Tarde' },
  { id: 't6', time: '14:30 - 16:00', period: 'Tarde' },
  { id: 't7', time: '16:00 - 17:30', period: 'Tarde' },
  { id: 't8', time: '17:30 - 19:00', period: 'Tarde' },
  { id: 't9', time: '19:00 - 20:30', period: 'Noche' },
  { id: 't10', time: '20:30 - 22:00', period: 'Noche' },
  { id: 't11', time: '22:00 - 23:30', period: 'Madrugada' }
];

export const ADS_IMAGE_PRO_TIP = 'https://lh3.googleusercontent.com/aida-public/AB6AXuDOMZdAxBcXSJf_JwBnqwgeP1ogZ8_rVejyzCOVOxUUx0eu0imfhiJEzfdbRgIUYm7_jZ3Bm1J2N8tg2UlCFrUgc5AYdkvmxQSHd9w4kuonYCuxMCSKejRcT6SYAnKCRnXIC7JBTMLGVoezorHAUOUCLJ1MhTNB2iNdEsI2FkosqHEbNkXqkf9tkKqXdE0upcLpDtnJolSBSKPWOdiFNAtu5LGbKyRNEVShuh6OhYZ_H61AVbYk38FaqCUIxMmn0nB8444PHtBf0-M';

export const SPORT_CATEGORIES = [
  {
    id: 'padel',
    name: 'Padel Pro League',
    image: '/images/court-1.jpg',
    tag: 'POPULAR',
    description: 'La liga de pádel más rápida y divertida de la ciudad.'
  },
  {
    id: 'futbol',
    name: 'Fútbol 5 & 7',
    image: '/images/court-2.jpg',
    tag: 'SINTÉTICO',
    description: 'Pastos artificiales profesionales con iluminación nocturna.'
  },
  {
    id: 'basquet',
    name: 'Basketball',
    image: '/images/basketball-silhouette.jpg',
    tag: 'DUELA PRO',
    description: 'Duelas profesionales techadas para retos urbanos.'
  },
  {
    id: 'tenis',
    name: 'Tenis Classic',
    image: '/images/court-3.jpg',
    tag: 'ARCILLA Y RÁPIDA',
    description: 'Canchas históricas con el mantenimiento perfecto.'
  }
];
