import { Court } from './types';

export const INITIAL_COURTS: Court[] = [
  {
    id: 'court-1',
    backendId: 1,
    name: 'Cancha Central Padel 1',
    sport: 'padel',
    type: 'Indoor',
    club: 'Club Raqueta Polanco',
    city: 'CDMX',
    score: 4.9,
    pricePerHour: 20,
    imageUrl: '/images/court-1.jpg',
    address: 'Campos Elíseos 134, Polanco, CDMX, México',
    isAvailable: true,
  },
  {
    id: 'court-2',
    backendId: 2,
    name: 'Cancha 4 Grand Slam',
    sport: 'tenis',
    type: 'Arcilla',
    club: 'Santa Fe Sports Center',
    city: 'CDMX',
    score: 4.7,
    pricePerHour: 25,
    imageUrl: '/images/court-2.jpg',
    address: 'Av. Vasco de Quiroga 2000, Lomas de Santa Fe, CDMX, México',
    isAvailable: true,
    upcomingSpots: true,
  },
  {
    id: 'court-3',
    backendId: 3,
    name: 'Estadio Urbano Sky 5',
    sport: 'futbol',
    type: 'Sintético',
    club: 'Roof Garden Arena',
    city: 'Roma Norte, CDMX',
    score: 4.8,
    pricePerHour: 30,
    imageUrl: '/images/court-3.jpg',
    address: 'Álvaro Obregón 154, Roma Norte, CDMX, México',
    isAvailable: true,
  },
  {
    id: 'court-4',
    backendId: 4,
    name: 'Duela NBA Pro',
    sport: 'basquet',
    type: 'Duela',
    club: 'Centro Deportivo Coyoacán',
    city: 'Coyoacán, CDMX',
    score: 5.0,
    pricePerHour: 10,
    imageUrl: '/images/court-4.jpg',
    address: 'Aguayo 23, Culhuacán, Coyoacán, CDMX, México',
    isAvailable: true,
  },
  {
    id: 'court-5',
    backendId: 5,
    name: 'Padel Club Vista Hermosa',
    sport: 'padel',
    type: 'Outdoor',
    club: 'Club Raqueta Lomas',
    city: 'Lomas, CDMX',
    score: 4.6,
    pricePerHour: 15,
    imageUrl: '/images/court-5.jpg',
    address: 'Paseo de la Reforma 4000, Lomas de Vista Hermosa, CDMX, México',
    isAvailable: false,
  },
  {
    id: 'court-6',
    backendId: 6,
    name: 'Arena Pro Tenis Smash',
    sport: 'tenis',
    type: 'Rápida',
    club: 'Club de Tenis San Ángel',
    city: 'San Ángel, CDMX',
    score: 4.9,
    pricePerHour: 25,
    imageUrl: '/images/court-6.jpg',
    address: 'Altavista 12, San Ángel, Álvaro Obregón, CDMX, México',
    isAvailable: true,
  },
  {
    id: 'court-7',
    backendId: 7,
    name: 'Estadio Campo de Fútbol 7',
    sport: 'futbol',
    type: 'Pasto Sintético Pro',
    club: 'Club Fútbol Condesa',
    city: 'La Condesa, CDMX',
    score: 4.9,
    pricePerHour: 35,
    imageUrl: '/images/court-7.jpg',
    address: 'Nuevo León 230, Hipódromo Condesa, CDMX, México',
    isAvailable: true,
  },
  {
    id: 'court-8',
    backendId: 8,
    name: 'Padel Dome Satélite',
    sport: 'padel',
    type: 'Techada',
    club: 'Padel Dome Satélite',
    city: 'Naucalpan, Edomex',
    score: 4.8,
    pricePerHour: 25,
    imageUrl: '/images/court-8.jpg',
    address: 'Circuito Novelistas 20, Ciudad Satélite, Naucalpan, Estado de México',
    isAvailable: true,
    upcomingSpots: true,
  },
  {
    id: 'court-9',
    backendId: 9,
    name: 'Sunset Basket Court',
    sport: 'basquet',
    type: 'Concreto Pro',
    club: 'Unidad Deportiva Cuauhtémoc',
    city: 'CDMX',
    score: 4.5,
    pricePerHour: 10,
    imageUrl: '/images/court-9.jpg',
    address: 'Eje Central Lázaro Cárdenas, Guerrero, CDMX, México',
    isAvailable: true,
  }
];

export const MOCK_TIME_SLOTS = [
  { id: 't1', time: '07:00 - 08:30', period: 'Mañana' },
  { id: 't2', time: '08:30 - 10:00', period: 'Mañana' },
  { id: 't3', time: '10:00 - 11:30', period: 'Mañana' },
  { id: 't4', time: '11:30 - 13:00', period: 'Mañana' },
  { id: 't5', time: '13:00 - 14:30', period: 'Tarde' },
  { id: 't6', time: '14:30 - 16:00', period: 'Tarde' },
  { id: 't7', time: '16:00 - 17:30', period: 'Tarde' },
  { id: 't8', time: '17:30 - 19:00', period: 'Tarde' },
  { id: 't9', time: '19:00 - 20:30', period: 'Noche' },
  { id: 't10', time: '20:30 - 22:00', period: 'Noche' },
  { id: 't11', time: '22:00 - 23:30', period: 'Madrugada' }
];

export const ADS_IMAGE_PRO_TIP = '/images/ad-protip.jpg';

export const SPORT_CATEGORIES = [
  {
    id: 'padel',
    name: 'Padel Pro League',
    image: '/images/sport-padel.jpg',
    tag: 'POPULAR',
    description: 'La liga de pádel más rápida y divertida de la ciudad.'
  },
  {
    id: 'futbol',
    name: 'Fútbol 5 & 7',
    image: '/images/sport-futbol.jpg',
    tag: 'SINTÉTICO',
    description: 'Pastos artificiales profesionales con iluminación nocturna.'
  },
  {
    id: 'basquet',
    name: 'Basketball',
    image: '/images/sport-basquet.jpg',
    tag: 'DUELA PRO',
    description: 'Duelas profesionales techadas para retos urbanos.'
  },
  {
    id: 'tenis',
    name: 'Tenis Classic',
    image: '/images/court-3.jpg',
    tag: 'ARCILLA Y RÁPIDA',
    description: 'Canchas históricas con el mantenimiento perfecto.'
  }
];
