[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/panel"
  to = "/panel/index.html"
  status = 200

[[redirects]]
  from = "/panel/*"
  to = "/panel/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
